### ISSUE TITLE
Is this working with JIT?

### ISSUE THREAD

**Issue by swamidass** [davidwebca/tailwindcss-group-variants#3]
In my attempt, it seems to be impossible to get it to work with JIT tailwind.

**Comment by davidwebca** [comment]
It should be, or it was up until a few days ago (I was still using it). But I'll be deprecating this officially soon. With the release of Tailwind 3, with JIT mode enabled by default and some more magic to detect and stack variants automatically, it's easier than ever to add custom variants / named group variants.

Example: https://play.tailwindcss.com/Gp4tfEXDYU?file=config

**Comment by kotgakapainor** [comment]
@davidwebca thank you for this plugin and also for providing a solution for tailwind v3. Take care
